language: node_js
node_js:
  - "8"
cache:
  apt: true
  directories:
    - node_modules 
branches:
  only:
    - source
before_install:
  - export TZ='Asia/Shanghai' # 更改时区
install:
  - npm install
script:
  - hexo clean
  - hexo g
  - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git config user.name "alef"  #修改name
  - git config user.email "cyb19950118@163.com"  #修改email
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master  #Travis_Token是在Travis中配置环境变量的名称
env:
 global:
   - GH_REF: github.com/YanBaoC/YanBaoC.github.io.git  #设置GH_REF，注意更改yourname
notifications:
  email:
    - cyb19950118@163.com
  on_success: change
  on_failure: always
